# Generated by Django 4.2.7 on 2023-11-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_day',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
    ]
